CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID TEXT,
    PRODUCT_NAME TEXT,
    SUPPLIER_ID TEXT,
    CATEGORY_ID TEXT,
    UNIT_TEXT,
    PRICE_REAL
);

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT_TEXT, PRICE_REAL)
VALUES
('1', 'PEARS SOAP', '1', '1', '10 BOXES* 20 BAGS', 18),
('2', 'PEARS BODY WASH', '1', '1', '24-12 OZ BOTTLES', 19),
('3', 'DOVE SOAP', '1', '2', '10 BOXES* 20 BAGS', 10),
('4', 'DOVE BODY WASH', '2', '2', '48-2 OZ JARS', 22),
('5', 'PENCILS', '2', '2', '36 BOXES', 21.35),
('6', 'PENCILS', '2', '2', '36 BOXES', 21.35);



SELECT * FROM PRODUCTS

SELECT COUNT(PRODUCT_ID) AS Product_Count
FROM PRODUCTS;

SELECT AVG(PRICE_REAL) AS Average_Price
FROM PRODUCTS;

SELECT SUM(PRICE_REAL) AS Total_Price
FROM PRODUCTS;

SELECT COUNT(DISTINCT(PRODUCT_NAME))
FROM PRODUCTS;

SELECT DISTINCT(PRODUCT_NAME)
FROM PRODUCTS;

SELECT * FROM PRODUCTS
WHERE UNIT_TEXT LIKE '1%';